apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab1-step3
spec:
  replicas: 5
  selector:
    matchLabels:
      app: lab1-step3
  template:
    metadata:
      labels:
        app: lab1-step3
    spec:
      containers:
      - name: lab1-step3
        image: lab1_step3
        ports:
        - containerPort: 80

